Add Google Pay support
aron123/node-barion pull request #71
Opened 2022-11-28 02:13 UTC by stephenmcd

Hi there, 

I'm working on adding Barion to our samples project for Google Pay, you can see it here: https://github.com/google-pay/pay-server-demos

This PR adds Google Pay to the library, it will close #62.

Thanks for making the library available.

2022-12-04 12:10 UTC, aron123 requested changes

2022-12-04 12:10 UTC, aron123 commented on lib/domain/GooglePay.js
> + * @see {@link https://docs.barion.com/Payment-Start-v2|Barion API Documentation}
Please change docs url to: https://docs.barion.com/Payment-StartPaymentWithGoogleToken-v3

2022-12-04 12:10 UTC, aron123 commented on lib/domain/GooglePay.js
> +const schema = Joi.object({
Docs refers this as an extension of the `StartPayment` schema, please use schema extension here: https://joi.dev/api/?v=17.7.0#objectkeysschema

2022-12-04 12:10 UTC, aron123 commented on lib/services.js
> +function googlePay(environment, options) {
googlePay -> startPaymentWithGoogleToken

2022-12-04 12:10 UTC, aron123 commented on lib/barion.js
> +Barion.prototype.googlePay = function (options, callback) {
googlePay -> startPaymentWithGoogleToken

2022-12-04 12:14 UTC, aron123 commented
Thanks for your contribution, I've requested some changes to the code.

In addition, the following have to be done before publishing this feature (I can work on these, if you don't want to):
- [ ] README documentation
- [ ] unit and integration tests

2025-04-01 08:48 UTC, zekageri commented
Will this ever be integrated?

2025-04-06 18:16 UTC, aron123 commented
The project is currently in an abandoned state due to lack of time. I am not currently working on new development, but happy to accept pull requests. Upon request, I can also fix minor bugs and update dependencies.

2025-10-24 20:41 UTC, aron123 commented
Resolved by #85

2025-10-24 20:41 UTC, closed without merging